POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6ImpvaG5hd3Jhd3JAVGVmc2FmYXNmc2Fmc3QuY29tIiwiaWF0IjoxNzYwMTM5NjgxLCJleHAiOjE3NjAxNDMyODEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Vf5RpfwbFgMpEhvQIjDP0plVjKKocpHQyP7BrLvXs74
{
  "title": "What's new with NestJS?",
  "postType": "post",
  "slug": "new-with-nestjs55667765gfafsfffff555",
  "status": "draft",
  "content": "This is the test post's content",
  "schema": { "@context": "https://schema.org", "@type": "Person" },
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2025-10-03T11:45:36.124Z",
  "metaOptions": {
    "metaValue": {
      "sidebarEnabled": false
    }
  },
  "tags": [4,6]
}  