POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "What's new with NestJS?",
  "postType": "post",
  "slug": "new-with-nestjs",
  "status": "draft",
  "content": "This is the test post's content",
  "schema": "{\n \"@context\": \"https://schema.org\",\n \"@type\": \"Person\"\n}",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2025-10-03T11:45:36.124Z",
  "tags": ["nestjs", "typescript"],
  "metaOptions": [
    {
      "key": "testKey",
      "value": 20
    }
  ]
}  