POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6ImpvaG5hd3Jhd3JAVGVmc2FmYXNmc2Fmc3QuY29tIiwiaWF0IjoxNzYwMTgzMjQ5LCJleHAiOjE3NjAxODY4NDksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.6q_Csr1zLCP1NBXzv2yL9MrkICD25eWJJlsCF2yEr5M

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJpYXQiOjE3NjAxODMyNDksImV4cCI6MTc2MDI2OTY0OSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.P-7TLk61A_sdE7wlN02ZACb46vUlUVESPWuoCKyNC3w"
}

